-- REMOVE DATA
DELETE FROM PERSON;
DELETE FROM CATEGORY;

-- REMOVE TABLE AND SEQUENCE
DROP TABLE CATEGORY;
DROP SEQUENCE SQ_CATEGORY;

-- REMOVE TABLE AND SEQUENCE
DROP TABLE PERSON;
DROP SEQUENCE SQ_PERSON;


