-- PERSON CREATION
CREATE TABLE PERSON (
	PERSON NUMBER,
	EMAIL VARCHAR2(100) UNIQUE NOT NULL,
	PASSWORD VARCHAR2(1000) NOT NULL,
	PERSON_TOKEN VARCHAR2(1000) NOT NULL,
	FIRST_NAME VARCHAR2(100) NOT NULL,
	LAST_NAME VARCHAR2(100) NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	MOD_DATE DATE,
	PRIMARY KEY(PERSON)
);

-- PERSON SEQUENCE
CREATE SEQUENCE SQ_PERSON NOCACHE;

-- CATEGORY CREATION
CREATE TABLE CATEGORY(
	CATEGORY NUMBER,
	PERSON NUMBER NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	DESCRIPTION VARCHAR2(200) NOT NULL,
	ADD_DATE DATE DEFAULT SYSDATE,
	MOD_DATE DATE,
	PRIMARY KEY(CATEGORY),
	FOREIGN KEY(PERSON) REFERENCES PERSON(PERSON)
);

-- CATEGORY SEQUENCE
CREATE SEQUENCE SQ_CATEGORY NOCACHE;
